<STRUCTURE> -> <STRUCTURE>|<SHAPE>;<STRUCTURE>.
<SHAPE> -> <TRIANGLE>|<SQUARE>.
<TRIANGLE> -> <POINT><POINT><POINT>.
<SQUARE> -> <POINT><POINT><POINT><POINT>.
<POINT> -> <BASEPOINT>|<GENERALPOINT>.
<BASEPOINT> -> startBase | middleBase | endBase | upperRightCorner | upperMiddleRight | upperLeftCorner | upperMiddleLeft.
<GENERALPOINT> -> maxX | maxY | maxZ | minX | minY | minZ.