<STRUCTURE> -> <SHAPE>;|<SHAPE>;<STRUCTURE>.
<SHAPE> -> <TRIANGLE>|<SQUARE>.
<TRIANGLE> -> tri(<POINT>,<POINT>,<POINT>).
<SQUARE> -> cuad(<POINT>,<POINT>,<POINT>,<POINT>).
<POINT> -> <BASEPOINT>|<GENERALPOINT>.
<BASEPOINT> -> startBase | middleBase | endBase | upperRightCorner | upperMiddleRight | upperLeftCorner | upperMiddleLeft.
<GENERALPOINT> -> maxX | maxY | maxZ | minX | minY | minZ.