<PLANE> -> <PLANESPEC>;<STRUCTURE>.
<PLANESPEC> -> plane(<N>,<N>,<N>,<N>).
<STRUCTURE> -> <SHAPE>;<SHAPE>;<SHAPE>;|<SHAPE>;<STRUCTURE>.
<SHAPE> -> <TRIANGLE>|<SQUARE>.
<TRIANGLE> -> tri(<POINT>,<POINT>,<POINT>).
<SQUARE> -> cuad(<POINT>,<POINT>,<POINT>,<POINT>).
<POINT> -> <OP>(<POINT>,<POINT>)|<BASEPOINT>|<GENERALPOINT>|'N('<NATURAL>).
<OP> -> '+'|'-'.
<BASEPOINT> -> startBase | middleBase | endBase | upperRightCorner | upperMiddleRight | upperLeftCorner | upperMiddleLeft.
<GENERALPOINT> -> maxX | maxY | maxZ | minX | minY | minZ.
<NATURAL> -> <N>,<N>,<N>. 
<N> -> 5|10|20|30|50.
<ANGLE> -> <N>|70|88.